
import static java.util.Collections.min;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rrr101
 */
public class GamePage extends javax.swing.JFrame {

    /**
     * Creates new form GamePage
     */
    Deck gameDeck = new Deck();
    int playerPoints ;
    int dealerPoints ;
    
    
    public GamePage() 
    {   
        gameDeck.shuffle();
        gameDeck.shuffle();
        gameDeck.shuffle();
        
        initComponents();
        
        this.playerPoints = 0;
        this.dealerPoints = 0;
    }
    
    public GamePage(int a, int b)
    {
        gameDeck.shuffle();
        
        if(a<10 && b<10)
        initComponents();
        else
        dispose();
        
        playerPoints = b;
        dealerPoints = a;
        
        dealerWin.setText(Integer.toString(a));
        playerWin.setText(Integer.toString(b));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerGuess = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        dealGuess = new javax.swing.JLabel();
        card1 = new javax.swing.JLabel();
        playerWin = new javax.swing.JLabel();
        dealerWin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerGuess.setText("Enter your Guess");
        playerGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerGuessActionPerformed(evt);
            }
        });
        getContentPane().add(playerGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 130, 30));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        dealGuess.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dealGuess.setForeground(new java.awt.Color(255, 255, 255));
        dealGuess.setText("Dealer Guess");
        getContentPane().add(dealGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 140, 30));

        card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1fv.png"))); // NOI18N
        card1.setText("Card 1");
        getContentPane().add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, 100));

        playerWin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        playerWin.setForeground(new java.awt.Color(255, 255, 255));
        playerWin.setText("playerPoints");
        getContentPane().add(playerWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        dealerWin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dealerWin.setForeground(new java.awt.Color(255, 255, 255));
        dealerWin.setText("dealerPoints");
        getContentPane().add(dealerWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dealer points");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 50));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player Points");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 470, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerGuessActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        
        Integer playGuess, dealerGuess;
        int dealerDifference, playerDifference;
        
         
        
        card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1fv.png")));
        
            Random rand = new Random();
            playGuess= Integer.parseInt(playerGuess.getText());
            dealerGuess = rand.nextInt((13-1)+1)+1;
            Hand gameHand = new Hand();
            gameHand.addCard(gameDeck.draw());
            
            
            card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+gameHand.lastCard().getSuitAsString()+"/"+gameHand.lastCard().getValueAsString()+".png")));
            
            dealerDifference = gameHand.getHandValue() - dealerGuess;
            playerDifference = gameHand.getHandValue() - playGuess;
            
            
            //to take care of negative differences
            if(dealerDifference < 0)
                dealerDifference = dealerDifference * -1 ;
            else if(playerDifference < 0)
                playerDifference = playerDifference * -1;
            
            
            dealGuess.setText(Integer.toString(dealerGuess));
            
            if(playerDifference < dealerDifference || gameHand.getHandValue() == playGuess)
            {
                
                playerPoints++;
                WinPage w = new WinPage(dealerPoints, playerPoints);
                w.setVisible(true);
              
                
                
            }
            
            else if(playerDifference > dealerDifference || gameHand.getHandValue() == dealerGuess)
            {
                
                dealerPoints++;
                LosePage l = new LosePage(dealerPoints, playerPoints);
                l.setVisible(true);
               
            }
            else if(dealerDifference==playerDifference)
            {
                
                dealerPoints++;
                playerPoints++;
                WinPage w = new WinPage(dealerPoints, playerPoints);
                w.setVisible(true);

                
                
            }
            
            
            
           
            
            
             
       
        
        
        
        
        
        
        
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel card1;
    private javax.swing.JLabel dealGuess;
    private javax.swing.JLabel dealerWin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField playerGuess;
    private javax.swing.JLabel playerWin;
    // End of variables declaration//GEN-END:variables
}
